// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class CajaMovimiento
{
    public int MovimientoId { get; set; }

    public int CajaId { get; set; }

    public DateTime Fecha { get; set; }

    public string TipoMovimiento { get; set; }

    public int ReferenciaId { get; set; }

    public decimal Monto { get; set; }

    public virtual Caja Caja { get; set; }
}