// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Caja
{
    public int CajaId { get; set; }

    public DateTime FechaApertura { get; set; }

    public DateTime? FechaCierre { get; set; }

    public decimal MontoInicial { get; set; }

    public decimal? MontoCierre { get; set; }

    public decimal TotalLavados { get; set; }

    public decimal TotalVentas { get; set; }

    public decimal? TotalIngresos { get; set; }

    public string UsuarioId { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<CajaMovimiento> CajaMovimiento { get; set; } = new List<CajaMovimiento>();

    public virtual ICollection<HistorialCierre> HistorialCierre { get; set; } = new List<HistorialCierre>();

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();
}