// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UI.Models;

namespace UI.Models
{
    public partial class CarwashSystemContext
    {
        private ICarwashSystemContextProcedures _procedures;

        public virtual ICarwashSystemContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CarwashSystemContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICarwashSystemContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CarwashSystemContextProcedures : ICarwashSystemContextProcedures
    {
        private readonly CarwashSystemContext _context;

        public CarwashSystemContextProcedures(CarwashSystemContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_DashboardResult>> sp_DashboardAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<sp_DashboardResult>("EXEC @returnValue = [op].[sp_Dashboard]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_ProductosMasVendidosResult>> sp_ProductosMasVendidosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<sp_ProductosMasVendidosResult>("EXEC @returnValue = [op].[sp_ProductosMasVendidos]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
