// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UI.Models;

public partial class CarwashSystemContext : DbContext
{
    public CarwashSystemContext(DbContextOptions<CarwashSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Caja> Caja { get; set; }

    public virtual DbSet<CajaMovimiento> CajaMovimiento { get; set; }

    public virtual DbSet<HistorialCierre> HistorialCierre { get; set; }
    public virtual DbSet<LavadoServicios> LavadoServicios { get; set; }

    public virtual DbSet<Lavados> Lavados { get; set; }

    public virtual DbSet<Lavados_View> Lavados_View { get; set; }

    public virtual DbSet<Marcas> Marcas { get; set; }

    public virtual DbSet<Modelos> Modelos { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Servicios> Servicios { get; set; }

    public virtual DbSet<TiposVehiculo> TiposVehiculo { get; set; }

    public virtual DbSet<Venta> Venta { get; set; }

    public virtual DbSet<VentaDetalle> VentaDetalle { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Caja>(entity =>
        {
            entity.HasKey(e => e.CajaId).HasName("PK__Caja__A74F870767EFACEA");

            entity.ToTable("Caja", "op");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.FechaApertura)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaCierre).HasColumnType("datetime");
            entity.Property(e => e.MontoCierre).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.MontoInicial).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalIngresos)
                .HasComputedColumnSql("([TotalLavados]+[TotalVentas])", true)
                .HasColumnType("decimal(11, 2)");
            entity.Property(e => e.TotalLavados).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UsuarioId)
                .IsRequired()
                .HasMaxLength(450);
        });

        modelBuilder.Entity<CajaMovimiento>(entity =>
        {
            entity.HasKey(e => e.MovimientoId).HasName("PK__CajaMovi__BF923C2C54961698");

            entity.ToTable("CajaMovimiento", "op");

            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Monto).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TipoMovimiento)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Caja).WithMany(p => p.CajaMovimiento)
                .HasForeignKey(d => d.CajaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CajaMovimiento_Caja");
        });

        modelBuilder.Entity<HistorialCierre>(entity =>
        {
            entity.HasKey(e => e.HistorialId).HasName("PK__Historia__9752068F388183EF");

            entity.ToTable("HistorialCierre", "op");

            entity.Property(e => e.FechaCierre).HasColumnType("datetime");
            entity.Property(e => e.MontoCierre).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalIngresos).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalLavados).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UsuarioId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.Caja).WithMany(p => p.HistorialCierre)
                .HasForeignKey(d => d.CajaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HistorialCierre_Caja");
        });

        modelBuilder.Entity<LavadoServicios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LavadoSe__3214EC07B5449A7C");

            entity.ToTable("LavadoServicios", "op");

            entity.HasIndex(e => new { e.LavadoId, e.ServicioId }, "UQ_Lavado_Servicio").IsUnique();

            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Lavado).WithMany(p => p.LavadoServicios)
                .HasForeignKey(d => d.LavadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LavadoServicios_Lavado");

            entity.HasOne(d => d.Servicio).WithMany(p => p.LavadoServicios)
                .HasForeignKey(d => d.ServicioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LavadoServicios_Servicio");
        });

        modelBuilder.Entity<Lavados>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lavados__3214EC07DD15A27E");

            entity.ToTable("Lavados", "op");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("PENDIENTE");
            entity.Property(e => e.FechaCierre).HasColumnType("datetime");
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Placa).HasMaxLength(20);
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Marca).WithMany(p => p.Lavados)
                .HasForeignKey(d => d.MarcaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lavados_Marca");

            entity.HasOne(d => d.TipoVehiculo).WithMany(p => p.Lavados)
                .HasForeignKey(d => d.TipoVehiculoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lavados_TipoVehiculo");
        });

        modelBuilder.Entity<Lavados_View>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Lavados_View", "op");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FechaCierre).HasColumnType("datetime");
            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");
            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Placa).HasMaxLength(20);
            entity.Property(e => e.TipoVehiculo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Marcas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Marcas__3214EC070AFD8C86");

            entity.ToTable("Marcas", "cat");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.TipoVehiculo).WithMany(p => p.Marcas)
                .HasForeignKey(d => d.TipoVehiculoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Marca_TipoVehiculo");
        });

        modelBuilder.Entity<Modelos>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Modelos__3214EC074FEF1634");

            entity.ToTable("Modelos", "cat");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Marca).WithMany(p => p.Modelos)
                .HasForeignKey(d => d.MarcaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Modelo_Marca");
        });

        modelBuilder.Entity<Productos>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC07D5DE028E");

            entity.ToTable("Productos", "cat");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Servicios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Servicio__3214EC071417EF45");

            entity.ToTable("Servicios", "cat");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(250);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TiposVehiculo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TiposVeh__3214EC0745FD882F");

            entity.ToTable("TiposVehiculo", "cat");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Venta>(entity =>
        {
            entity.HasKey(e => e.VentaId).HasName("PK__Venta__5B4150AC546A561C");

            entity.ToTable("Venta", "op");

            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Pago).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Vuelto).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Caja).WithMany(p => p.Venta)
                .HasForeignKey(d => d.CajaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Venta_Caja");
        });

        modelBuilder.Entity<VentaDetalle>(entity =>
        {
            entity.HasKey(e => e.VentaDetalleId).HasName("PK__VentaDet__2DF62C377D1B2A14");

            entity.ToTable("VentaDetalle", "op");

            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SubTotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Venta).WithMany(p => p.VentaDetalle)
                .HasForeignKey(d => d.VentaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VentaDetalle_Venta");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}