// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class HistorialCierre
{
    public int HistorialId { get; set; }

    public int CajaId { get; set; }

    public DateTime FechaCierre { get; set; }

    public decimal MontoCierre { get; set; }

    public decimal TotalLavados { get; set; }

    public decimal TotalVentas { get; set; }

    public decimal TotalIngresos { get; set; }

    public string UsuarioId { get; set; }

    public virtual Caja Caja { get; set; }
}