// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UI.Models;

namespace UI.Models
{
    public partial interface ICarwashSystemContextProcedures
    {
        Task<List<sp_DashboardResult>> sp_DashboardAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_ProductosMasVendidosResult>> sp_ProductosMasVendidosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
