// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class LavadoServicios
{
    public int Id { get; set; }

    public int LavadoId { get; set; }

    public int ServicioId { get; set; }

    public decimal? Precio { get; set; }

    public virtual Lavados Lavado { get; set; }

    public virtual Servicios Servicio { get; set; }
}