// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Lavados_View
{
    public int Id { get; set; }

    public int TipoVehiculoId { get; set; }

    public string TipoVehiculo { get; set; }

    public int MarcaId { get; set; }

    public string Marca { get; set; }

    public int? ModeloId { get; set; }

    public string Modelo { get; set; }

    public string Placa { get; set; }

    public string Estado { get; set; }

    public DateTime FechaRegistro { get; set; }

    public DateTime? FechaCierre { get; set; }

    public decimal Total { get; set; }
}