// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Marcas
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int TipoVehiculoId { get; set; }

    public virtual ICollection<Lavados> Lavados { get; set; } = new List<Lavados>();

    public virtual ICollection<Modelos> Modelos { get; set; } = new List<Modelos>();

    public virtual TiposVehiculo TipoVehiculo { get; set; }
}