// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Modelos
{
    public int Id { get; set; }

    public int MarcaId { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public virtual Marcas Marca { get; set; }
}