// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UI.Models
{
    public partial class sp_DashboardResult
    {
        [Column("LavadosHoy", TypeName = "decimal(18,0)")]
        public decimal? LavadosHoy { get; set; }
        [Column("VentasHoy", TypeName = "decimal(18,0)")]
        public decimal? VentasHoy { get; set; }
        [Column("IngresosHoy", TypeName = "decimal(18,0)")]
        public decimal? IngresosHoy { get; set; }
        public bool? CajaAbierta { get; set; }
        [Column("TotalCaja", TypeName = "decimal(18,0)")]
        public decimal? TotalCaja { get; set; }
    }
}
