// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UI.Models
{
    public partial class sp_ProductosMasVendidosResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Nombre { get; set; }
        public int? CantidadVendida { get; set; }
        [Column("TotalVendido", TypeName = "decimal(38,2)")]
        public decimal? TotalVendido { get; set; }
    }
}
