// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class TiposVehiculo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Lavados> Lavados { get; set; } = new List<Lavados>();

    public virtual ICollection<Marcas> Marcas { get; set; } = new List<Marcas>();
}