// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Venta
{
    public int VentaId { get; set; }

    public int CajaId { get; set; }

    public decimal Total { get; set; }

    public decimal Pago { get; set; }

    public decimal Vuelto { get; set; }

    public DateTime Fecha { get; set; }

    public virtual Caja Caja { get; set; }

    public virtual ICollection<VentaDetalle> VentaDetalle { get; set; } = new List<VentaDetalle>();
}